# Generated by Django 3.2.9 on 2021-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211207_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
