# Generated by Django 3.2.9 on 2021-12-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211207_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
