# Generated by Django 3.2.9 on 2021-12-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20211207_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='todouser',
            name='lastname',
        ),
    ]
