version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: todoapp

  backend:
    build: ./todoapp
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'todoapp.settings.prod'
    command: bash -c "
        python manage.py migrate &&
        gunicorn todoapp.wsgi -b 0.0.0.0:8080
      "

  nginx:
    build: ./nginx
    privileged: true
    ports:
      - "8000:80"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - nginx

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
